stages:
  - test
  - build

variables:
  GO_VERSION: "1.21"  # 根据你的 Go 版本需求调整
  BUILD_DIR: "build"

# 缓存 Go 模块以提高构建速度
cache:
  paths:
    - go/pkg/mod/

before_script:
  - apt-get update -qq && apt-get install -y -qq upx-ucl zip  # 安装 UPX 和 zip
  - go version  # 验证 Go 版本

test:
  stage: test
  image: golang:$GO_VERSION
  script:
    - go test -v ./...  # 运行所有测试

build:
  stage: build
  image: golang:$GO_VERSION
  script:
    - chmod +x build.sh
    - ./build.sh
  artifacts:
    paths:
      - $BUILD_DIR/
    expire_in: 1 week  # 制品保留时间
