stages:
  - test

variables:
  GO_VERSION: "1.21"  # 根据你的 Go 版本需求调整
  BUILD_DIR: "build"

# 缓存 Go 模块以提高构建速度
cache:
  paths:
    - go/pkg/mod/

before_script:
  - sed -i 's/deb.debian.org/mirrors.aliyun.com/g' /etc/apt/sources.list
  - sed -i 's/security.debian.org/mirrors.aliyun.com/g' /etc/apt/sources.list
  - apt-get update -qq
  - apt-get install -y -qq upx zip
  - go version  # 验证 Go 版本

test:
  stage: test
  image: golang:$GO_VERSION
  script:
    - echo "test"  # 运行所有测试


