stages:
  - build
  - release

variables:
  VERSION_TAG: "1.0.0"
  BUILD_DIR: "build"

# 缓存 Go 模块以提高构建速度
cache:
  paths:
    - go/pkg/mod/

before_script:
  - echo "重建阿里源配置..."
  


build:
  stage: build
  image: 622cd93839b7
  script:
    - go mod tidy
    - chmod +x build.sh
    - ./build.sh
  artifacts:
    paths:
      - $BUILD_DIR/
    expire_in: 1 week  # 制品保留时间

release:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  script:
    - echo "Creating release"
  release:
    tag_name: $VERSION_TAG
    name: "Release $VERSION_TAG"
    description: "$VERSION_TAG版本release build测试"

