stages:
  - test

variables:
  GO_VERSION: "1.21"  # 根据你的 Go 版本需求调整
  BUILD_DIR: "build"

# 缓存 Go 模块以提高构建速度
cache:
  paths:
    - go/pkg/mod/

before_script:
  - echo "重建阿里源配置..."
  # 删除旧配置
  - rm -f /etc/apt/sources.list /etc/apt/sources.list.d/*
  # 写入阿里源（假设是 Debian bookworm）
  - echo "deb http://mirrors.aliyun.com/debian/ bookworm main non-free non-free-firmware contrib" > /etc/apt/sources.list
  - echo "deb http://mirrors.aliyun.com/debian-security/ bookworm-security main" >> /etc/apt/sources.list
  - apt-get install -y -qq upx zip
  - go version  # 验证 Go 版本

test:
  stage: test
  image: golang:$GO_VERSION
  script:
    - echo "test"  # 运行所有测试


