version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: gxx
    binary: gxx
    env:
      - CGO_ENABLED=0
    goos:
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - "386"
      - arm
      - arm64
    flags:
      - -trimpath
    ldflags:
      - -s -w

upx:
  - ids: [gxx]
    enabled: true
    goos: ["windows", "linux"]
    goarch: ["amd64", "386"]
    compress: best

archives:
  - formats: ['zip']
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64{{- else if eq .Arch "386" }}i386{{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - "^*.md"
      - "^*.ya?ml"
